<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1623925825796' stop='1623925885934'>
    <name>Image Validation</name>
    <title>Image Validation</title>
    <test-cases>
        <test-case start='1623925825797' status='broken' stop='1623925885923'>
            <name>Verify the fullpage image</name>
            <title>Verify the fullpage image</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-1'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-91.0.4472.77'/>
            </parameters>
            <steps>
                <step start='1623925825805' status='broken' stop='1623925885915'>
                    <name>POST /session/:sessionId/url</name>
                    <title>POST /session/:sessionId/url</title>
                    <attachments>
                        <attachment title='Request' source='ca30ff33-e9d8-4716-a6fd-5415ed683da2-attachment.json' type='application/json' size='73'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Timeout of 60000ms exceeded. The execution in the test "Image Validation Verify the fullpage image" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (E:\docker Aswin\test\TS_02imgFullPageVerification.js)</message>
                <stack-trace>Error: Timeout of 60000ms exceeded. The execution in the test "Image Validation Verify the fullpage image" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (E:\docker Aswin\test\TS_02imgFullPageVerification.js)
                    at createTimeoutError (E:\docker Aswin\node_modules\mocha\lib\errors.js:498:15)
                    at Test.Runnable._timeoutError (E:\docker Aswin\node_modules\mocha\lib\runnable.js:431:10)
                    at Timeout.&lt;anonymous> (E:\docker Aswin\node_modules\mocha\lib\runnable.js:246:24)
                    at listOnTimeout (internal/timers.js:557:17)
                    at processTimers (internal/timers.js:500:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>